services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  db_test:
    image: postgres:15
    env_file:
      - .env-test
    environment:
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASSWORD_TEST}
      POSTGRES_DB: ${DB_NAME_TEST}
      POSTGRES_HOST: ${DB_HOST_TEST}
    ports:
      - 5433:5432
    volumes:
      - postgres-data-test:/var/lib/postgresql/data

volumes:
  postgres-data:
  postgres-data-test:
