services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}

    ports:
      - ${DB_PORT}:5432

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
