"""Добавил тип DATE из алхимии модели BookingsOrm сдедал описание уник

Revision ID: 667f15fbc4c8
Revises: 03ef7d68fe1b
Create Date: 2024-11-15 02:01:49.771924

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "667f15fbc4c8"
down_revision: Union[str, None] = "03ef7d68fe1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "facilities", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "facilities", type_="unique")
    # ### end Alembic commands ###
