"""Добавил тип DATE из алхимии модели BookingsOrm

Revision ID: 1a9d2c79fd15
Revises: c157ba24eae6
Create Date: 2024-11-12 05:37:12.887030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a9d2c79fd15"
down_revision: Union[str, None] = "c157ba24eae6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
