"""hashed_password вместо password в моделе пользователя

Revision ID: b42b7f658456
Revises: eabbfdc2f72e
Create Date: 2024-10-16 04:22:18.709510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b42b7f658456"
down_revision: Union[str, None] = "eabbfdc2f72e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.String(length=200), nullable=False),
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
